// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO8hYy61Yhln6roJjs28lfK6j9ylcqxts',
    appId: '1:873397291520:web:4cd2f258821682eb1d66e5',
    messagingSenderId: '873397291520',
    projectId: 'harbest-mustardgreenanalytics',
    authDomain: 'harbest-mustardgreenanalytics.firebaseapp.com',
    storageBucket: 'harbest-mustardgreenanalytics.firebasestorage.app',
    measurementId: 'G-NN2Q1Q5L9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWlP4irI-nu2Vi5WxiBKNNRsHlWSwdsyE',
    appId: '1:873397291520:android:a186f19afb8bbcc11d66e5',
    messagingSenderId: '873397291520',
    projectId: 'harbest-mustardgreenanalytics',
    storageBucket: 'harbest-mustardgreenanalytics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtD4YTKjv1JdPXYPn6RKFkay0A7zrUvuU',
    appId: '1:873397291520:ios:34e87955e31599a41d66e5',
    messagingSenderId: '873397291520',
    projectId: 'harbest-mustardgreenanalytics',
    storageBucket: 'harbest-mustardgreenanalytics.firebasestorage.app',
    iosClientId: '873397291520-jr99gs9i6qt20gav3brtqea5gk70924l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationHarbest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtD4YTKjv1JdPXYPn6RKFkay0A7zrUvuU',
    appId: '1:873397291520:ios:34e87955e31599a41d66e5',
    messagingSenderId: '873397291520',
    projectId: 'harbest-mustardgreenanalytics',
    storageBucket: 'harbest-mustardgreenanalytics.firebasestorage.app',
    iosClientId: '873397291520-jr99gs9i6qt20gav3brtqea5gk70924l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationHarbest1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO8hYy61Yhln6roJjs28lfK6j9ylcqxts',
    appId: '1:873397291520:web:c1d1bce19d398ccf1d66e5',
    messagingSenderId: '873397291520',
    projectId: 'harbest-mustardgreenanalytics',
    authDomain: 'harbest-mustardgreenanalytics.firebaseapp.com',
    storageBucket: 'harbest-mustardgreenanalytics.firebasestorage.app',
    measurementId: 'G-0YH2354CRL',
  );
}
